### ISSUE TITLE
dynamiccompile tests not successful on NixOS

### ISSUE THREAD

**Issue by ThomasMader** [ldc-developers/ldc#2497]
I had similar problems with the asan tests in 1.5.0 and just removed them but with 1.7.0 those tests work. Instead have similar error messages for the dynamiccompile tests.

@JohanEngelen suggested that the dynamiccompile shared lib probably needs the same rpath logic as ASan in http://forum.dlang.org/post/nqbvuieabgedanbbqbnc@forum.dlang.org

The output of the build/test run:

CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   ldc-jit-rt-so

Here is the error for array:

771: FAIL: LDC :: dynamiccompile/array.d (140 of 190)
771: ******************** TEST 'LDC :: dynamiccompile/array.d' FAILED ********************
771: Script:
771: --
771: /tmp/nix-build-ldcBuild-1.7.0.drv-0/ldc-1.7.0-src/build/bin/ldc2 -enable-dynamic-compile -run /private/tmp/nix-build-ldcBuild-1.7.0.drv-0/ldc-1.7.0-src/tests/dynamiccompile/array.d
771: --
771: Exit Code: 2
771:
771: Command Output (stdout):
771: --
771: $ "/tmp/nix-build-ldcBuild-1.7.0.drv-0/ldc-1.7.0-src/build/bin/ldc2" "-enable-dynamic-compile" "-run" "/private/tmp/nix-build-ldcBuild-1.7.0.drv-0/ldc-1.7.0-src/tests/dynamiccompile/array.d"
771: # command stderr:
771: dyld: Library not loaded: libldc-jit.77.dylib
771:   Referenced from: /var/folders/rw/hkyl0vdn02jfvt1s8_2wxvkr000x9j/T/array-30ec308-4bc080
771:   Reason: image not found
771: Error: /var/folders/rw/hkyl0vdn02jfvt1s8_2wxvkr000x9j/T/array-30ec308-4bc080 failed with status: -2
771: Error: message: Abort trap: 6
771: Error: program received signal 2 (Interrupt: 2)
771:
771: error: command failed with exit status: 2

...

771: Testing Time: 29.06s
771: ********************
771: Failing Tests (15):
771:     LDC :: dynamiccompile/array.d
771:     LDC :: dynamiccompile/calls.d
771:     LDC :: dynamiccompile/classes.d
771:     LDC :: dynamiccompile/dump_handler.d
771:     LDC :: dynamiccompile/empty_jit_modules.d
771:     LDC :: dynamiccompile/globals.d
771:     LDC :: dynamiccompile/globals_types.d
771:     LDC :: dynamiccompile/lambdas.d
771:     LDC :: dynamiccompile/params_ctors.d
771:     LDC :: dynamiccompile/recursive_call.d
771:     LDC :: dynamiccompile/simple.d
771:     LDC :: dynamiccompile/struct_init.d
771:     LDC :: dynamiccompile/thread_local.d
771:     LDC :: dynamiccompile/throw.d
771:     LDC :: dynamiccompile/tls_workaround_opt.d
771:
771:   Expected Passes    : 145
771:   Unsupported Tests  : 30
771:   Unexpected Failures: 15
1/1 Test #771: lit-tests ........................***Failed   30.71 sec

**Comment by JohanEngelen** [comment]
@Hardcode84 Can you have a look at this?

**Comment by Hardcode84** [comment]
@JohanEngelen I don't have access to OSX machine right now and I can only try to blindly duplicate asan logic.

**Comment by ThomasMader** [comment]
@Hardcode84 I can run the dynamiccompile unittests on OSX or even do more if you tell me what to do.

**Comment by Hardcode84** [comment]
@ThomasMader Thanks, I will prepare branch with fixes.

**Comment by Hardcode84** [comment]
@ThomasMader #2503 Can you please try compile and test my branch `https://github.com/Hardcode84/ldc/tree/jit_osx_link_fix`

**Comment by ThomasMader** [comment]
@Hardcode84 I saw that @JohanEngelen was faster. See https://github.com/ldc-developers/ldc/pull/2503#issuecomment-357527755

**Comment by kinke** [comment]
This should be working now.

**Comment by ThomasMader** [comment]
This is still an issue for me with ldc 1.14.0-beta1 with Nix on MacOS.

Could someone explain to me why libldc-jit.77.dylib is not found?
It's supposed to be created by ldc right?

**Comment by kinke** [comment]
> It's supposed to be created by ldc right?

It is; it's part of the `all` build target, see its [CMake script](https://github.com/ldc-developers/ldc/blob/master/runtime/jit-rt/DefineBuildJitRT.cmake). From our macOS CI [job log](https://circleci.com/gh/ldc-developers/ldc/6907):

```
[14/68] Linking CXX shared library lib/libldc-jit.2.0.84.dylib
```

**Comment by ThomasMader** [comment]
`ls /private/tmp/nix-build-ldcBuild-1.14.0-beta1.drv-2/ldc-1.14.0-beta1-src/build/lib/libldc-jit*` gives me:

```
/private/tmp/nix-build-ldcBuild-1.14.0-beta1.drv-2/ldc-1.14.0-beta1-src/build/lib/libldc-jit-rt.a
/private/tmp/nix-build-ldcBuild-1.14.0-beta1.drv-2/ldc-1.14.0-beta1-src/build/lib/libldc-jit.2.0.84.dylib
/private/tmp/nix-build-ldcBuild-1.14.0-beta1.drv-2/ldc-1.14.0-beta1-src/build/lib/libldc-jit.84.dylib
/private/tmp/nix-build-ldcBuild-1.14.0-beta1.drv-2/ldc-1.14.0-beta1-src/build/lib/libldc-jit.dylib
```

I still get the following error:

```
dyld: Library not loaded: libldc-jit.84.dylib
  Referenced from: /private/tmp/nix-build-ldcBuild-1.14.0-beta1.drv-2/lit_tmp_TkpNsw/tls_workaround_opt-7ab51fb-077bc5
  Reason: image not found
```

I read through https://blogs.oracle.com/dipol/dynamic-libraries,-rpath,-and-mac-os and thought it might be a good idea to make the otool checks but the referencing binary doesn't exist.
Is it automatically deleted by the lit test?
Is there a way to keep that file to be able to diagnose the problem?

Anyway here is the output of `otool -D /private/tmp/nix-build-ldcBuild-1.14.0-beta1.drv-2/ldc-1.14.0-beta1-src/build/lib/libldc-jit.84.dylib`:

```
/private/tmp/nix-build-ldcBuild-1.14.0-beta1.drv-2/ldc-1.14.0-beta1-src/build/lib/libldc-jit.84.dylib:
libldc-jit.84.dylib
```

**Comment by kinke** [comment]
> Is it automatically deleted by the lit test? 
> Is there a way to keep that file to be able to diagnose the problem?

It's all in your (old) output:

```
/tmp/nix-build-ldcBuild-1.7.0.drv-0/ldc-1.7.0-src/build/bin/ldc2 -enable-dynamic-compile -run /private/tmp/nix-build-ldcBuild-1.7.0.drv-0/ldc-1.7.0-src/tests/dynamiccompile/array.d
```

Just remove the `-run`, as that removes the executable after execution, and then you can check the RPATH.

**Comment by ThomasMader** [comment]
I found out that the test is working with the final package and noticed lines like this in the build process:

/nix/store/a8b8nq7a3knbbk3fz6jm467z0rph69hz-ldcBuild-1.14.0-beta1/lib/libldc-jit.2.0.84.dylib: fixing dylib

This led me to https://github.com/NixOS/nixpkgs/pull/22571/commits/04fa8e006cf662a9cdefa52162e006304ad8877d#diff-ae25cc0a6109438682d7b688b27a4b4aR23 and made me realize that it is necessary on Darwin with Nix that the dylibs are fixed.

I run the tests while the package is build and therefore the fixes are not done yet by Nix.

**Comment by ThomasMader** [comment]
I was wrong about NixOS/nixpkgs@04fa8e0#diff-ae25cc0a6109438682d7b688b27a4b4aR23 .

The difference between the installed dylib and the dylib used inside the package build is that the installed has the full path as id.
This can be set with `install_name_tool -id "<id>" <name>.dylib`.

One solution to the problem is to set the DYLD_LIBRARY_PATH to the build/lib directory so the dylib can be found.
That could also be done inside the D source file: `// RUN: env DYLD_LIBRARY_PATH=/tmp/nix-build-ldcBuild-1.14.0-beta1.drv-5/ldc-1.14.0-beta1-src/build/lib/ %ldc -enable-dynamic-compile -run %s`

As far as I understood it the id of the dylib is changed at the install step so I don't get why the dylib is found when built on a normal macOS machine.

**Comment by kinke** [comment]
What's supposed to happen is that the lib is simply found by properly setting the executable's RPATH (specified in `ldc2.conf`, used automatically when linking with `-enable-dynamic-compile` and visible in the linker command line (add `-v` to ldc2 command line)). IIRC, the ID of the installed lib is `@rpath/<name>.dylib` (you could check that out by inspecting the lib of an official OSX package); not sure about the intermediate lib.

**Comment by ThomasMader** [comment]
The problem is described also under https://nixos.org/nixpkgs/manual/#sec-darwin as:

```
On darwin libraries are linked using absolute paths, libraries are resolved by their install_name at link time.
...
Even if the libraries are linked using absolute paths and resolved via their install_name correctly, tests can sometimes fail to run binaries. This happens because the checkPhase runs before the libraries are installed.

This can usually be solved by running the tests after the installPhase or alternatively by using DYLD_LIBRARY_PATH. More information about this variable can be found in the dyld(1) manpage.
```

The `DYLD_LIBRARY_PATH` would solve the issue for me but I needed to put it in the D source file for lit to set the variable properly.
Maybe one solution would be to set the variable in `tests/lit.site.cfg.in` in case of Darwin?
The proposed solution to run the tests after the installPhase doesn't work as the lit tests don't use the installed package but the files from the build.

This is the outcome in the package build:

```
otool -L /var/folders/wq/m1dnr42s42n5msqk2v8l0lfc0000gn/T/array-cc7d415-e1a32f
/var/folders/wq/m1dnr42s42n5msqk2v8l0lfc0000gn/T/array-cc7d415-e1a32f:
	libldc-jit.84.dylib (compatibility version 84.0.0, current version 2.0.84)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)
```

And this is the outcome after the package is installed and the dylib is changed and works correctly:

```
otool -L /var/folders/wq/m1dnr42s42n5msqk2v8l0lfc0000gn/T/array-f82c628-91a4aa
/var/folders/wq/m1dnr42s42n5msqk2v8l0lfc0000gn/T/array-f82c628-91a4aa:
	/nix/store/69d8zvgcd2zmk3zaxs530045k9z4ig16-ldcBuild-1.14.0-beta1/lib/libldc-jit.84.dylib (compatibility version 84.0.0, current version 2.0.84)
	/nix/store/zk205w9w6fd77mv80iydcnp7c8s1him6-Libsystem-osx-10.11.6/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
```

**Comment by ThomasMader** [comment]
I would like to just test the final binaries but that doesn't work as many of the tests are using the binaries from the build.
This makes for sure sense as those tests are made for upstream development.
But I like the idea of having my package tested against all available tests as it brings up problems very fast.

I am now fixing the IDs of the libs with a bash script. But before that I need to build all test runners with `make -j$NIX_BUILD_CORES all-test-runners` because this step is producing dylib libs too.

And now I am going a little off topic.

The funny thing though is that I am getting C++ linker errors when I try to test everything with `ctest -V -j $NIX_BUILD_CORES --output-on-failure`

1511: $ ":" "RUN: at line 3"
1511: $ "/tmp/nix-build-ldcUnittests-1.14.0-beta1.drv-34/ldc-1.14.0-beta1-src/build/bin/ldc2" "-conf=" "-I/tmp/nix-build-ldcUnittests-1.14.0-beta1.drv-34/ldc-1.14.0-beta1-src/tests/baremetal/inputs" "-run" "/private/tmp/nix-build-ldcUnittests-1.14.0-beta1.drv-34/ldc-1.14.0-beta1-src/tests/baremetal/classes.d"
1511: # command stderr:
1511: ld: library not found for -lc++

When I run them independently like in the semaphoreci sh script in the repo those errors vanish.
I don't have a clue what the cause of this could be. 
Anyway, with the following sequence I am down to one missing test it seems.

```
        # Build default lib test runners
        make -j$NIX_BUILD_CORES all-test-runners
        ${fixNames} 

      # Build and run LDC D unittests. 
      ctest --output-on-failure -R "ldc2-unittest"
      # Run LIT testsuite.
      ctest -V -R "lit-tests"
    
      # Run DMD testsuite.
      DMD_TESTSUITE_MAKE_ARGS=-j$NIX_BUILD_CORES DMD=${ldcBuild.out}/bin/ldmd2 CC=$CXX ctest -V -R "dmd-testsuite"

      # Run default lib unittests
      ctest -j$NIX_BUILD_CORES --output-on-failure -E "ldc2-unittest|lit-tests|dmd-testsuite|druntime-test-shared"
```

The last remaining error is:

```
1500/1504 Test #1496: druntime-test-shared ...............................................................***Failed    2.07 sec
make: Entering directory '/private/tmp/nix-build-ldcUnittests-1.14.0-beta1.drv-37/ldc-1.14.0-beta1-src/runtime/druntime/test/shared'
/tmp/nix-build-ldcUnittests-1.14.0-beta1.drv-37/ldc-1.14.0-beta1-src/build/bin/ldmd2 -fPIC -shared   -w -I../../src -I../../import -Isrc -defaultlib= -debuglib= -dip1000 -L/tmp/nix-build-ldcUnittests-1.14.0-beta1.drv-37/ldc-1.14.0-beta1-src/build/lib/libdruntime-ldc-shared.2.0.84.dylib -link-defaultlib-shared -O -release -of/tmp/nix-build-ldcUnittests-1.14.0-beta1.drv-37/ldc-1.14.0-beta1-src/build/runtime/druntime-test-shared/lib.so src/lib.d -L-ldl
/tmp/nix-build-ldcUnittests-1.14.0-beta1.drv-37/ldc-1.14.0-beta1-src/build/bin/ldmd2   -w -I../../src -I../../import -Isrc -defaultlib= -debuglib= -dip1000 -L/tmp/nix-build-ldcUnittests-1.14.0-beta1.drv-37/ldc-1.14.0-beta1-src/build/lib/libdruntime-ldc-shared.2.0.84.dylib -link-defaultlib-shared -O -release -of/tmp/nix-build-ldcUnittests-1.14.0-beta1.drv-37/ldc-1.14.0-beta1-src/build/runtime/druntime-test-shared/link src/link.d -L/tmp/nix-build-ldcUnittests-1.14.0-beta1.drv-37/ldc-1.14.0-beta1-src/build/runtime/druntime-test-shared/lib.so
Testing link
/tmp/nix-build-ldcUnittests-1.14.0-beta1.drv-37/ldc-1.14.0-beta1-src/build/runtime/druntime-test-shared/link
/tmp/nix-build-ldcUnittests-1.14.0-beta1.drv-37/ldc-1.14.0-beta1-src/build/bin/ldmd2   -w -I../../src -I../../import -Isrc -defaultlib= -debuglib= -dip1000 -L/tmp/nix-build-ldcUnittests-1.14.0-beta1.drv-37/ldc-1.14.0-beta1-src/build/lib/libdruntime-ldc-shared.2.0.84.dylib -link-defaultlib-shared -O -release -of/tmp/nix-build-ldcUnittests-1.14.0-beta1.drv-37/ldc-1.14.0-beta1-src/build/runtime/druntime-test-shared/load src/load.d -L-ldl
Testing load
/tmp/nix-build-ldcUnittests-1.14.0-beta1.drv-37/ldc-1.14.0-beta1-src/build/runtime/druntime-test-shared/load
clang -Wall -Wl,-rpath,/tmp/nix-build-ldcUnittests-1.14.0-beta1.drv-37/ldc-1.14.0-beta1-src/build/lib -o /tmp/nix-build-ldcUnittests-1.14.0-beta1.drv-37/ldc-1.14.0-beta1-src/build/runtime/druntime-test-shared/linkD src/linkD.c /tmp/nix-build-ldcUnittests-1.14.0-beta1.drv-37/ldc-1.14.0-beta1-src/build/runtime/druntime-test-shared/lib.so -ldl  -pthread
Testing linkD
/tmp/nix-build-ldcUnittests-1.14.0-beta1.drv-37/ldc-1.14.0-beta1-src/build/runtime/druntime-test-shared/linkD
clang -Wall -Wl,-rpath,/tmp/nix-build-ldcUnittests-1.14.0-beta1.drv-37/ldc-1.14.0-beta1-src/build/lib -o /tmp/nix-build-ldcUnittests-1.14.0-beta1.drv-37/ldc-1.14.0-beta1-src/build/runtime/druntime-test-shared/linkDR src/linkDR.c /tmp/nix-build-ldcUnittests-1.14.0-beta1.drv-37/ldc-1.14.0-beta1-src/build/lib/libdruntime-ldc-shared.2.0.84.dylib -ldl  -pthread
Testing linkDR
/tmp/nix-build-ldcUnittests-1.14.0-beta1.drv-37/ldc-1.14.0-beta1-src/build/runtime/druntime-test-shared/linkDR
clang -Wall -Wl,-rpath,/tmp/nix-build-ldcUnittests-1.14.0-beta1.drv-37/ldc-1.14.0-beta1-src/build/lib -o /tmp/nix-build-ldcUnittests-1.14.0-beta1.drv-37/ldc-1.14.0-beta1-src/build/runtime/druntime-test-shared/loadDR src/loadDR.c -ldl  -pthread
Testing loadDR
/tmp/nix-build-ldcUnittests-1.14.0-beta1.drv-37/ldc-1.14.0-beta1-src/build/runtime/druntime-test-shared/loadDR /tmp/nix-build-ldcUnittests-1.14.0-beta1.drv-37/ldc-1.14.0-beta1-src/build/lib/libdruntime-ldc-shared.2.0.84.dylib
/tmp/nix-build-ldcUnittests-1.14.0-beta1.drv-37/ldc-1.14.0-beta1-src/build/bin/ldmd2   -w -I../../src -I../../import -Isrc -defaultlib= -debuglib= -dip1000 -L/tmp/nix-build-ldcUnittests-1.14.0-beta1.drv-37/ldc-1.14.0-beta1-src/build/lib/libdruntime-ldc-shared.2.0.84.dylib -link-defaultlib-shared -O -release -of/tmp/nix-build-ldcUnittests-1.14.0-beta1.drv-37/ldc-1.14.0-beta1-src/build/runtime/druntime-test-shared/finalize src/finalize.d -L-ldl
Testing finalize
/tmp/nix-build-ldcUnittests-1.14.0-beta1.drv-37/ldc-1.14.0-beta1-src/build/runtime/druntime-test-shared/finalize
make: *** [Makefile:24: /tmp/nix-build-ldcUnittests-1.14.0-beta1.drv-37/ldc-1.14.0-beta1-src/build/runtime/druntime-test-shared/finalize.done] Illegal instruction: 4
make: Leaving directory '/private/tmp/nix-build-ldcUnittests-1.14.0-beta1.drv-37/ldc-1.14.0-beta1-src/runtime/druntime/test/shared'
```

**Comment by ThomasMader** [comment]
Closing as the dynamiccompile tests work on MacOS now.
