### ISSUE TITLE
Latest xcode results in lots of linker warnings

### ISSUE THREAD

**Issue by schveiguy** [ldc-developers/ldc#4501]
A sample for when I build a simple app with ldc 1.34.0  with xcode 15.0 (there are a lot of these):

```
ld: warning: no platform load command found in '/Users/steves/.dub/cache/numbers/~master/build/application-debug-WophZRlX_VEn3wfrspNcCQ/numbers.o', assuming: macOS
ld: warning: no platform load command found in '/Users/steves/ldc2-1.34.0-osx-universal/lib-arm64/libphobos2-ldc.a[2](curl.o)', assuming: macOS
ld: warning: no platform load command found in '/Users/steves/ldc2-1.34.0-osx-universal/lib-arm64/libphobos2-ldc.a[8](zlib.o)', assuming: macOS
ld: warning: no platform load command found in '/Users/steves/ldc2-1.34.0-osx-universal/lib-arm64/libphobos2-ldc.a[9](comparison.o)', assuming: macOS
ld: warning: no platform load command found in '/Users/steves/ldc2-1.34.0-osx-universal/lib-arm64/libphobos2-ldc.a[11](iteration.o)', assuming: macOS
```

It's unfortunate, Apple seems to change the linker rules every release...

**Comment by kinke** [comment]
The apparently common workaround is to use `-L-ld_classic`:
* https://github.com/desktop-app/cmake_helpers/commit/aaedaede705ab908b1bbaf026c59b4379b0d1cf8
* https://github.com/crystal-lang/crystal/issues/13846
* https://projects.blender.org/blender/blender/pulls/110243/files

**Comment by drpriver** [comment]
`-L-w` also suppresses the warnings (though it suppresses all linker warnings).

**Comment by jacob-carlborg** [comment]
Hmm, I thought this would be a thing that LLVM does automatically.

I implemented a fix for a similar warning for DMD a couple of years ago. It was never merged but it shows more or less what needs to be done [1].

[1] https://github.com/dlang/dmd/pull/10476

**Comment by JohanEngelen** [comment]
Fixed in #4534

**Comment by jacob-carlborg** [comment]
Did this not make the 1.36.0 release? I still get these warnings. Actually, with 1.35.0 I get these warnings for both object files from Phobos/druntime and for the object files compiled from my own code. With 1.36.0 I only get warnings for object files from Phobos/druntime.

**Comment by JohanEngelen** [comment]
This did make it into the release (and the beta), but indeed I also see linker warnings with the released binary. When building LDC on my own machine, I do not get any warnings. Somehow related to how release packages are built? (on what OS, etc.)

**Comment by kinke** [comment]
I assume you guys are talking about arm64, with a potential culprit being https://github.com/ldc-developers/ldc/blob/530d41be11e92901f797ebbbc1dc695df4af06e9/.github/actions/3-build-cross/action.yml#L82, and possibly some more stuff. - One month of beta, still not enough. :(

**Comment by jacob-carlborg** [comment]
> I assume you guys are talking about arm64

Yes.

> One month of beta, still not enough. :(

Sorry about that. I tried the beta, I just assumed the fix wasn't included. It's not mentioned in the release notes or in the changelog. But it seems that individual bug fixes are not listed there. I have projects that automatically test all betas and latest versions of the compiler. But it won't catch these kinds of issues, since it builds and runs fine anyway.

I suggested creating a test, a few days after the fix was merged: https://github.com/ldc-developers/ldc/pull/4534#issuecomment-1837154300.
