### ISSUE TITLE
MSVC build, lots and lots of warnings

### ISSUE THREAD

**Issue by rikkimax** [ldc-developers/ldc#988]
Compiler: 0.15.2 beta2 win64
Test program:

```D
import std.stdio:writeln;
void main() {writeln("Hi!");}
```

Compiles + runs fine.
Only issue is well, umm https://gist.github.com/rikkimax/2db36ccd7ef65daeef84
Lots and lots of warnings.

So, given how simple that program is, any chance for a significant decrease in number of second definitions?
Or at the very least, make a note of it somewhere?

**Comment by redstar** [comment]
I noted this in the announcement: http://forum.dlang.org/post/ccuhfwbuzzqvpqpnhfhf@forum.dlang.org
I am investigating the issue.

**Comment by p0nce** [comment]
I have the exact problem :), also compilation is very slow.

**Comment by redstar** [comment]
I am wondering if the root cause is this change mentioned in the LLVM release notes:

    Comdats are now ortogonal to the linkage. LLVM will not create comdats for weak linkage globals and the frontends are responsible for explicitly adding them.

**Comment by redstar** [comment]
Fixed in merge-2.067 branch.

**Comment by kinke** [comment]
The situation has improved a lot, thanks Kai @redstar, but it's still present - 460 warnings left, see
https://ci.appveyor.com/project/kinke/ldc/build/job/etqtastpn8ppi47c

**Comment by redstar** [comment]
I see. I missed some `enum`s or so.

**Comment by kinke** [comment]
Perfect, thanks a lot Kai.

**Comment by kinke** [comment]
Damn, there are still some remains, I should have checked more carefully. :/
Only Phobos test runner fails to link, see https://ci.appveyor.com/project/kinke/ldc/build/job/1qmk2thhqxv5cdsf (https://ci.appveyor.com/project/kinke/ldc/build/1.0.138/job/1qmk2thhqxv5cdsf#L1355 till line 1561).

**Comment by kinke** [comment]
Finally fixed by https://github.com/ldc-developers/ldc/pull/1087 - at least there are no more linking errors when building the runtimes and their test runners.
